version: "3"
services:
  user_api:
    container_name: user_api
    restart: always
    build: ./user_api
    ports:
    - "7070:3000" 
    depends_on:
    - mongo
 
  product_api:
    container_name: product_api
    restart: always
    build: ./product_api
    ports:
    - "8080:3000" 
    depends_on:
    - mongo
    
  order_api:
    container_name: order_api
    restart: always
    build: ./order_api
    ports:
    - "9090:3000" 
    depends_on:
    - mongo  
    
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongodata:/data/db 
    ports:
      - "27017:27017"
volumes:
  mongodata: